# 🎌 StudioOtaku - Anime Latino Premium Funding
# Apoya el desarrollo de la mejor plataforma de anime en español latino

# GitHub Sponsors - Patrocinio mensual en GitHub
# github: [studiootaku977]

# Ko-fi - Donaciones de café para el desarrollador
ko_fi: studiootaku977

# Patreon - Suscripciones mensuales con beneficios exclusivos
patreon: studiootaku

# Buy Me A Coffee - Donaciones rápidas y sencillas
buy_me_a_coffee: studiootaku977

# PayPal y enlaces personalizados de donación
custom: [
  "https://paypal.me/injenieroensistemas",
  "mailto:studiootaku6@gmail.com"
]

# ¿Por qué apoyar StudioOtaku?
# ✅ Anime HD sin publicidad molesta
# ✅ Servidores rápidos y confiables  
# ✅ Catálogo actualizado constantemente
# ✅ Mejor alternativa a Cuevana y AnimeLatinoHD
# ✅ Desarrollo de app móvil Android
# ✅ Hosting y mantenimiento de servidores
